### ISSUE TITLE
Issues for fixing the front-end

### ISSUE THREAD

**Issue by theosenoussaoui** [ESGI-4IW1/Insteat#49]
## Fixes to implement regarding the front-end integration.
- [x] Implement forms themes to avoid redundance in forms type.
- [x] Fix errors and messages for forms.
- [x] Fix the overflow issue in login and registering.
- [x] Create error template for codes 404, 500, etc.
- [x] Add autoprefixer permanently into the Webpack Config.
- [x] Fixing the overlapping issues on the index and with the navigation bar.
- [x] Fix the Javascript implementation of the navbar transition to pure CSS + JS transition. 
- [x] Improve the overall design of the homepage. That includes all the changes regarding the components that are already defined and the ones that impacts all the text (check the Sketch mockups)
- [ ] Improve the calendar design without breaking anything regarding booking and ordering.
- [x] Finish the mailing template for registration/booking/annulation confirmation.
- [x] Fix the footer behavior and height during scrolling.

**Comment by wdelenclos** [comment]
Do the navbar transition at last

**Comment by theosenoussaoui** [comment]
#61 for "Fix errors and messages for forms."

**Comment by theosenoussaoui** [comment]
#63 covers these issues, but please accept #61 first : 

* Implement forms themes to avoid redundance in forms type.
* Fix errors and messages for forms.
* Fix the overflow issue in login and registering.

**Comment by theosenoussaoui** [comment]
#64 for : 
* Add autoprefixer permanently into the Webpack Config.
